server {
  listen 443 ssl;
  server_name p4.localhost localhost;
  ssl_certificate /run/p4-runtime/tls_cert.pem;
  ssl_certificate_key /run/p4-runtime/tls_key.pem;
  ssl_protocols TLSv1.2 TLSv1.3;
  add_header X-Content-Type-Options nosniff always;
  add_header Referrer-Policy no-referrer always;

  location /api/ {
    proxy_pass http://api:8000;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-Port 8444;
    proxy_set_header X-Request-ID $request_id;
  }

    location = /oidc/callback {
        proxy_pass http://web/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /oidc/ {
    proxy_pass http://oidc:8080/oidc/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-Port 8444;
    proxy_set_header X-Forwarded-Host $host;
  }

  location / {
    proxy_pass http://web:80;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
  }
}

server {
  listen 80;
  return 301 https://$host:8444$request_uri;
}
