import { useEffect, useMemo, useState } from 'react'
import './business-loop.css'

type Alert = { alert_id:string; metric_id:string; entity_type:string; entity_id:string; severity:string; title:string; status:string; assignee_id:string|null; sla_level:string; due_at:string; overdue:boolean; escalation_status:string; change_rate:number|null; run_id:string }
type Timeline = { timeline_event_id:string; event_type:string; actor:string; actor_type:string; timestamp:string; before_state:string|null; after_state:string|null; reason:string }
type ReportVersion = { report_version_id:string; version:number; status:string; created_by:string; created_at:string; dataset_version:string; semantic_version:string; run_id:string; summary:string }
type ReportRow = { report_id:string; title:string; owner:string; status:string; current_version:ReportVersion; review_status:string|null; published_at:string|null; archived_at:string|null }
type MetricVersion = { metric_version_id:string; metric_id:string; version:string; name:string; business_definition:string; formula:string; unit:string; dimensions:string[]; time_grain:string; source_tables:string[]; owner:string; effective_from:string|null; effective_to:string|null; change_reason:string; impact_analysis:{ impact_level?:string; downstream_checks?:Array<{consumer:string;affected:boolean}> }; status:string; review_outcome:string|null }

async function request<T>(path:string, token:string, init?:RequestInit):Promise<T> {
  const response = await fetch(path, { ...init, headers:{ Authorization:`Bearer ${token}`, ...(init?.body?{'Content-Type':'application/json'}:{}), ...(init?.headers||{}) } })
  const body = await response.json().catch(() => null)
  if (!response.ok) throw new Error(body?.detail?.message || body?.error?.message || `请求失败（${response.status}）`)
  return body as T
}
function Status({value}:{value:string}) { const tone=['PUBLISHED','APPROVED','VERIFIED','CLOSED'].includes(value)?'ok':['P0','P1','REOPENED','REJECTED','RESOLVE_OVERDUE','ACK_OVERDUE'].includes(value)?'risk':'active'; return <span className={`p6-status ${tone}`}>{value}</span> }
function State({loading,error,retry}:{loading:boolean;error:string;retry:()=>void}) { return loading?<div className="p6-state">正在读取业务治理记录…</div>:<div className="p6-state error"><b>业务治理数据加载失败</b><span>{error}</span><button onClick={retry}>重新加载</button></div> }

export function BusinessAlertPage({token,start,end}:{token:string;start:string;end:string}) {
  const [rows,setRows]=useState<Alert[]>([]), [selectedId,setSelectedId]=useState(''), [timeline,setTimeline]=useState<Timeline[]>([])
  const [loading,setLoading]=useState(true), [working,setWorking]=useState(false), [error,setError]=useState(''), [feedback,setFeedback]=useState('')
  const [reason,setReason]=useState('经营预警闭环处置'), [assignee,setAssignee]=useState('analyst')
  const selected=rows.find(row=>row.alert_id===selectedId)||rows[0]
  const load=async(preferred?:string)=>{setLoading(true);setError('');try{const result=await request<{rows:Alert[]}>('/api/v1/alerts',token);setRows(result.rows);setSelectedId(preferred&&result.rows.some(row=>row.alert_id===preferred)?preferred:result.rows[0]?.alert_id||'')}catch(cause){setError(cause instanceof Error?cause.message:'预警加载失败')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[token])
  useEffect(()=>{if(!selected?.alert_id){setTimeline([]);return}request<{rows:Timeline[]}>(`/api/v1/alerts/${selected.alert_id}/timeline`,token).then(result=>setTimeline(result.rows)).catch(()=>setTimeline([]))},[selected?.alert_id,token])
  const generate=async()=>{setWorking(true);setFeedback('');try{const result=await request<{created:boolean;deduplicated:boolean;alert:Alert|null}>('/api/v1/alerts/generate',token,{method:'POST',body:JSON.stringify({metric_id:'charging_revenue',start,end_exclusive:end,threshold:.0001})});setFeedback(result.deduplicated?'同一规则与分析周期已去重，未重复创建预警。':result.created?'诊断规则已生成并持久化预警。':'本期指标未触发预警规则。');await load(result.alert?.alert_id)}catch(cause){setFeedback(cause instanceof Error?cause.message:'生成失败')}finally{setWorking(false)}}
  const act=async(action:string)=>{if(!selected)return;setWorking(true);setFeedback('');const body:Record<string,string>={reason};if(action==='assign')body.assignee_id=assignee;if(action==='resolve')body.summary='已核查经营指标、处置动作与证据链。';if(action==='verify')body.summary='验证结果满足关闭条件。';try{await request(`/api/v1/alerts/${selected.alert_id}/${action}`,token,{method:'POST',body:JSON.stringify(body)});setFeedback('状态变更已由服务端校验并写入时间线与审计。');await load(selected.alert_id)}catch(cause){setFeedback(cause instanceof Error?cause.message:'操作失败')}finally{setWorking(false)}}
  const next=selected?({OPEN:['assign','分派'],REOPENED:['assign','重新分派'],ASSIGNED:['acknowledge','确认'],ACKNOWLEDGED:['in-progress','开始处理'],IN_PROGRESS:['resolve','解决'],RESOLVED:['verify','验证'],VERIFIED:['close','关闭'],CLOSED:['reopen','重开']} as Record<string,[string,string]>)[selected.status]:undefined
  if(loading&&!rows.length)return <State loading error="" retry={()=>void load()}/>;if(error&&!rows.length)return <State loading={false} error={error} retry={()=>void load()}/>
  return <div className="p6-page alert-page" data-testid="p6-alert-center"><header className="p6-hero"><div><small>P6 · OPERATING ALERT GOVERNANCE</small><h2>经营预警中心</h2><p>诊断规则生成预警事件，状态机、SLA、通知尝试和审计由服务端统一执行。</p></div><button className="primary" disabled={working} onClick={()=>void generate()}>{working?'处理中…':'运行受控预警规则'}</button></header>{feedback&&<div className="p6-feedback">{feedback}</div>}<section className="p6-kpis"><article><span>预警总数</span><b>{rows.length}</b></article><article><span>待处理</span><b>{rows.filter(row=>!['CLOSED','VERIFIED'].includes(row.status)).length}</b></article><article><span>已逾期</span><b>{rows.filter(row=>row.overdue).length}</b></article><article><span>P0 / P1</span><b>{rows.filter(row=>['P0','P1'].includes(row.severity)).length}</b></article></section><section className="p6-grid split"><article className="p6-panel list"><header><h3>预警事件</h3><span>{rows.length} 条数据库记录</span></header>{rows.length?<div className="p6-table-wrap"><table><thead><tr><th>等级</th><th>指标 / 实体</th><th>状态</th><th>处理人</th><th>SLA</th></tr></thead><tbody>{rows.map(row=><tr className={selected?.alert_id===row.alert_id?'selected':''} key={row.alert_id} onClick={()=>setSelectedId(row.alert_id)}><td><Status value={row.severity}/></td><td><b>{row.metric_id}</b><small>{row.entity_type}/{row.entity_id}</small></td><td><Status value={row.status}/></td><td>{row.assignee_id||'待分派'}</td><td><b className={row.overdue?'overdue':''}>{row.overdue?'已逾期':row.sla_level}</b><small>{new Date(row.due_at).toLocaleString('zh-CN',{hour12:false})}</small></td></tr>)}</tbody></table></div>:<div className="p6-empty">尚无预警事件。运行受控规则后，符合阈值的诊断结果会持久化到这里。</div>}</article><article className="p6-panel detail"><header><h3>处置工作台</h3>{selected&&<Status value={selected.status}/>}</header>{selected?<><dl><div><dt>预警</dt><dd>{selected.title}</dd></div><div><dt>变化率</dt><dd>{selected.change_rate==null?'数据不足':`${(selected.change_rate*100).toFixed(2)}%`}</dd></div><div><dt>运行证据</dt><dd><code>{selected.run_id}</code></dd></div><div><dt>升级状态</dt><dd>{selected.escalation_status}</dd></div></dl><label>处置理由<input value={reason} onChange={event=>setReason(event.target.value)}/></label><label>处理人<input value={assignee} onChange={event=>setAssignee(event.target.value)}/></label><div className="p6-actions">{next&&<button className="primary" disabled={working} onClick={()=>void act(next[0])}>{next[1]}</button>}{selected.status==='OPEN'&&<button disabled={working} onClick={()=>void act('acknowledge')}>直接确认</button>}</div><h4>状态时间线</h4><div className="p6-timeline">{timeline.map(item=><div key={item.timeline_event_id}><i/><span><b>{item.before_state||'—'} → {item.after_state||'—'}</b><small>{item.event_type} · {item.actor}（{item.actor_type}）</small><em>{item.reason}</em></span></div>)}</div></>:<div className="p6-empty">选择一条预警查看处置详情。</div>}</article></section></div>
}

export function ReportGovernancePage({token,start,end}:{token:string;start:string;end:string}) {
  const [rows,setRows]=useState<ReportRow[]>([]),[selectedId,setSelectedId]=useState(''),[evidence,setEvidence]=useState<Record<string,unknown>|null>(null)
  const [loading,setLoading]=useState(true),[working,setWorking]=useState(false),[error,setError]=useState(''),[feedback,setFeedback]=useState(''),[reason,setReason]=useState('P6 报告治理流程操作')
  const selected=rows.find(row=>row.report_id===selectedId)||rows[0]
  const load=async(preferred?:string)=>{setLoading(true);setError('');try{const result=await request<{rows:ReportRow[]}>('/api/v1/reports',token);setRows(result.rows);setSelectedId(preferred&&result.rows.some(row=>row.report_id===preferred)?preferred:result.rows[0]?.report_id||'')}catch(cause){setError(cause instanceof Error?cause.message:'报告加载失败')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[token]);useEffect(()=>{setEvidence(null);if(!selected||!['PUBLISHED','ARCHIVED'].includes(selected.status))return;request<Record<string,unknown>>(`/api/v1/reports/${selected.report_id}/evidence`,token).then(setEvidence).catch(()=>setEvidence(null))},[selected?.report_id,selected?.status,token])
  const create=async()=>{setWorking(true);setFeedback('');try{const row=await request<ReportRow>('/api/v1/reports',token,{method:'POST',body:JSON.stringify({report_type:'monthly',start,end_exclusive:end,title:'经营分析月报'})});setFeedback('报告草稿与版本 1 已持久化。');await load(row.report_id)}catch(cause){setFeedback(cause instanceof Error?cause.message:'创建失败')}finally{setWorking(false)}}
  const act=async(name:string)=>{if(!selected)return;setWorking(true);setFeedback('');let body:Record<string,string>={reason};if(name==='versions')body={reason,summary:`经营报告版本 ${selected.current_version.version+1}`};if(['submit-review','approve','reject'].includes(name))body={reviewer:'system_reviewer',actor_type:'SYSTEM',comment:reason};if(name==='publish')body={publisher:'system_approver',actor_type:'SYSTEM',reason};try{await request(`/api/v1/reports/${selected.report_id}/${name}`,token,{method:'POST',body:JSON.stringify(body)});setFeedback('报告状态、版本与审核记录已更新并审计。');await load(selected.report_id)}catch(cause){setFeedback(cause instanceof Error?cause.message:'操作失败')}finally{setWorking(false)}}
  const buttons=selected?(selected.status==='DRAFT'||selected.status==='VERSIONED'?[['submit-review','提交审核'],['versions','新版本']]:selected.status==='IN_REVIEW'?[['approve','批准'],['reject','拒绝']]:selected.status==='APPROVED'?[['publish','发布']]:selected.status==='PUBLISHED'?[['archive','归档'],['versions','新版本']]:[]):[]
  if(loading&&!rows.length)return <State loading error="" retry={()=>void load()}/>;if(error&&!rows.length)return <State loading={false} error={error} retry={()=>void load()}/>
  return <div className="p6-page report-governance-page" data-testid="p6-report-center"><header className="p6-hero"><div><small>P6 · GOVERNED REPORT LIFECYCLE</small><h2>经营报告中心</h2><p>每次修改创建新版本；发布时冻结指标、查询哈希、数据版本与知识引用。</p></div><button className="primary" disabled={working} onClick={()=>void create()}>{working?'处理中…':'创建月报草稿'}</button></header>{feedback&&<div className="p6-feedback">{feedback}</div>}<section className="p6-grid split"><article className="p6-panel list"><header><h3>报告与版本</h3><span>{rows.length} 份报告</span></header>{rows.length?<div className="p6-table-wrap"><table><thead><tr><th>报告</th><th>版本</th><th>状态</th><th>创建者</th><th>审核 / 发布</th></tr></thead><tbody>{rows.map(row=><tr className={selected?.report_id===row.report_id?'selected':''} key={row.report_id} onClick={()=>setSelectedId(row.report_id)}><td><b>{row.title}</b><small>{row.report_id}</small></td><td>v{row.current_version.version}</td><td><Status value={row.status}/></td><td>{row.current_version.created_by}</td><td>{row.review_status||'未提交'}<small>{row.published_at?new Date(row.published_at).toLocaleString('zh-CN',{hour12:false}):'未发布'}</small></td></tr>)}</tbody></table></div>:<div className="p6-empty">尚无报告。创建后将形成可审核的数据库版本记录。</div>}</article><article className="p6-panel detail"><header><h3>版本治理</h3>{selected&&<Status value={selected.status}/>}</header>{selected?<><dl><div><dt>当前版本</dt><dd>v{selected.current_version.version} · {selected.current_version.status}</dd></div><div><dt>Dataset</dt><dd>{selected.current_version.dataset_version}</dd></div><div><dt>Semantic</dt><dd>{selected.current_version.semantic_version}</dd></div><div><dt>run_id</dt><dd><code>{selected.current_version.run_id}</code></dd></div></dl><label>流程理由<input value={reason} onChange={event=>setReason(event.target.value)}/></label><div className="p6-actions">{buttons.map(([name,label])=><button className={name==='publish'||name==='approve'?'primary':''} disabled={working} key={name} onClick={()=>void act(name)}>{label}</button>)}</div><h4>冻结证据</h4>{evidence?<div className="p6-evidence"><b>Evidence Snapshot 已冻结</b><code>{String(evidence.snapshot_hash)}</code><span>query_plan_hash：{String(evidence.query_plan_hash)}</span><span>sql_hash：{String(evidence.sql_hash)}</span></div>:<div className="p6-empty compact">发布后显示不可变 Evidence Snapshot。</div>}</>:<div className="p6-empty">选择报告查看版本治理。</div>}</article></section></div>
}

export function MetricGovernancePage({token}:{token:string}) {
  const [rows,setRows]=useState<MetricVersion[]>([]),[selectedId,setSelectedId]=useState(''),[formula,setFormula]=useState(''),[reason,setReason]=useState('P6 指标版本治理变更')
  const [loading,setLoading]=useState(true),[working,setWorking]=useState(false),[error,setError]=useState(''),[feedback,setFeedback]=useState('')
  const selected=rows.find(row=>row.metric_version_id===selectedId)||rows[0],metrics=useMemo(()=>new Set(rows.map(row=>row.metric_id)).size,[rows])
  const load=async(preferred?:string)=>{setLoading(true);setError('');try{const result=await request<{rows:MetricVersion[]}>('/api/v1/metrics/governance',token);setRows(result.rows);const next=preferred&&result.rows.some(row=>row.metric_version_id===preferred)?preferred:result.rows[0]?.metric_version_id||'';setSelectedId(next);setFormula(result.rows.find(row=>row.metric_version_id===next)?.formula||'')}catch(cause){setError(cause instanceof Error?cause.message:'指标加载失败')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[token]);useEffect(()=>{if(selected)setFormula(selected.formula)},[selected?.metric_version_id])
  const call=async(path:string,body?:Record<string,unknown>,method='POST')=>{setWorking(true);setFeedback('');try{const result=await request<MetricVersion>(path,token,{method,body:body?JSON.stringify(body):undefined});setFeedback('指标治理动作已完成并写入审计。');await load(result.metric_version_id||selected?.metric_version_id)}catch(cause){setFeedback(cause instanceof Error?cause.message:'操作失败')}finally{setWorking(false)}}
  const createDraft=async()=>{if(selected)await call('/api/v1/metrics/governance/drafts',{metric_id:selected.metric_id,change_reason:reason})}
  const act=async(name:string)=>{if(!selected)return;if(name==='save')return call(`/api/v1/metrics/governance/versions/${selected.metric_version_id}`,{formula,reason},'PATCH');if(name==='impact-analysis')return call(`/api/v1/metrics/governance/versions/${selected.metric_version_id}/impact-analysis`);return call(`/api/v1/metrics/governance/versions/${selected.metric_version_id}/${name}`,{reason})}
  const buttons=selected?.status==='DRAFT'?[['save','保存草稿'],['impact-analysis','影响分析'],...(selected.impact_analysis.downstream_checks?[['submit-review','提交审核']]:[])]:selected?.status==='REVIEW'?[['approve','批准'],['reject','拒绝']]:selected?.status==='APPROVED'?[['publish','发布']]:selected?.status==='PUBLISHED'?[['deprecate','停用'],['draft','新建版本']]:[]
  if(loading&&!rows.length)return <State loading error="" retry={()=>void load()}/>;if(error&&!rows.length)return <State loading={false} error={error} retry={()=>void load()}/>
  return <div className="p6-page metric-governance-page" data-testid="p6-metric-center"><header className="p6-hero"><div><small>P6 · METRIC GOVERNANCE</small><h2>指标治理中心</h2><p>已发布指标只通过新草稿、影响分析、审核与发布形成新版本，历史版本持续可追溯。</p></div><div className="p6-hero-count"><b>{metrics}</b><span>个治理指标</span></div></header>{feedback&&<div className="p6-feedback">{feedback}</div>}<section className="p6-grid split"><article className="p6-panel list"><header><h3>指标版本</h3><span>{rows.length} 个版本</span></header><div className="p6-table-wrap"><table><thead><tr><th>指标</th><th>版本</th><th>状态</th><th>Owner</th><th>单位 / 生效</th></tr></thead><tbody>{rows.map(row=><tr className={selected?.metric_version_id===row.metric_version_id?'selected':''} key={row.metric_version_id} onClick={()=>setSelectedId(row.metric_version_id)}><td><b>{row.name}</b><small>{row.metric_id}</small></td><td>{row.version}</td><td><Status value={row.status}/></td><td>{row.owner}</td><td>{row.unit}<small>{row.effective_from||'待发布'}</small></td></tr>)}</tbody></table></div></article><article className="p6-panel detail"><header><h3>指标版本治理</h3>{selected&&<Status value={selected.status}/>}</header>{selected?<><dl><div><dt>指标</dt><dd>{selected.name} · {selected.version}</dd></div><div><dt>维度</dt><dd>{selected.dimensions.join(', ')}</dd></div><div><dt>时间粒度</dt><dd>{selected.time_grain}</dd></div><div><dt>来源表</dt><dd>{selected.source_tables.join(', ')}</dd></div></dl><label>公式<textarea disabled={selected.status!=='DRAFT'} value={formula} onChange={event=>setFormula(event.target.value)}/></label><label>变更理由<input value={reason} onChange={event=>setReason(event.target.value)}/></label><div className="p6-actions">{buttons.map(([name,label])=>name==='draft'?<button key={name} disabled={working} onClick={()=>void createDraft()}>{label}</button>:<button key={name} className={name==='publish'||name==='approve'?'primary':''} disabled={working} onClick={()=>void act(name)}>{label}</button>)}</div><h4>影响分析</h4>{selected.impact_analysis.downstream_checks?<div className="p6-impact"><Status value={selected.impact_analysis.impact_level||'CHECKED'}/>{selected.impact_analysis.downstream_checks.map(item=><span key={item.consumer}>{item.consumer}<b>{item.affected?'受影响':'已检查'}</b></span>)}</div>:<div className="p6-empty compact">提交审核前必须执行公式、单位、来源、维度、粒度及下游消费者检查。</div>}</>:null}</article></section></div>
}
